# Copy this file to secrets.toml and fill in your values

# Simple username/password authentication
# Add your league members here
[users]
john = "password123"
sarah = "mypassword"
mike = "league2024"
alice = "pickem123"

# Optional: The Odds API for live betting lines
# Get free API key from: https://the-odds-api.com/
[odds_api]
key = "your-odds-api-key-here"