# Copy this file to secrets.toml and fill in your values

# Authentication configuration
[auth]
provider = "google"  # or your preferred OIDC provider
client_id = "your-client-id-here"
client_secret = "your-client-secret-here"
redirect_uri = "http://localhost:8501"  # Update for production deployment

# Optional: The Odds API for live betting lines
[odds_api]
key = "your-odds-api-key-here"